[compiler.solc]
ignore_paths = ["node_modules", ".woke-build", "venv", "lib","test","script", "beedle/test", "beedle/script"]
include_paths = ["src","lib"]

remappings = [

    "ds-test/=lib/solady/lib/ds-test/src/",
    "forge-std/=lib/openzeppelin-contracts/lib/forge-std/src/",
    "solmate/=lib/solmate/src/"    
]

[detectors]
exclude = []
ignore_paths = ["node_modules", ".woke-build", "venv", "lib"]

[testing]
cmd = "anvil"

[testing.anvil]
cmd_args = "--prune-history 100 --transaction-block-keeper 10  --steps-tracing "

[testing.ganache]
cmd_args = "-k istanbul -q"

[testing.hardhat]
cmd_args = ""
